### ISSUE TITLE
Hi, i got this problem when pre-training Condenser. I try several version of transformer to fix but it didn't work. Can you help me please

### ISSUE THREAD

**Issue by PNMinh286** [luyug/Condenser#12]
![image](https://user-images.githubusercontent.com/75312938/160802036-ae160584-c3e8-426b-87b6-dcbd899ad951.png)

**Comment by luyug** [comment]
It looks like you didn't point the code to the proper training data directory.

**Comment by PNMinh286** [comment]
> It looks like you didn't point the code to the proper training data directory.
Thank you for answering. I try ver 4.2.0 and it worked

**Comment by lvzii** [comment]
Function _remove_unused_columns(in latest transformers's trainer.py ) will set dataset to None. 
So  higher version transformers doesn't work.
