### ISSUE TITLE
CLS of which layers to use in Condenser? last layer CLS? sum of last four layers CLS?

### ISSUE THREAD

**Issue by mahdiabdollahpour** [luyug/Condenser#13]
Hi
Thanks for the nice repo. After pretraining, Condenser has the same architecture as BERT (condenser heads are removed). Which CLS layers worked best for neural IR? last layer CLS? the sum of the last four layers CLS? ....

**Comment by luyug** [comment]
We fine-tune the last backbone layer's CLS which is the one passed to the head during pre-training.

**Comment by luyug** [comment]
Closing for now. Feel free to re-open if you have new questions.
