### ISSUE TITLE
Error when continuing train from pretrained model

### ISSUE THREAD

**Issue by dzunglt24** [luyug/Condenser#6]
Hi,

Thank you for your great work.

I try to run your code on my machine: 

> torch 1.8.1 transformers: 4.9.2 

but face the error below. 

> Traceback (most recent call last):
>   File "run_pre_training.py", line 202, in <module>
>     main()
>   File "run_pre_training.py", line 172, in main
>     trainer.train(model_path=model_path)
>   File "/home/dzge/.conda/envs/workspace/lib/python3.8/site-packages/transformers/trainer.py", line 1072, in train
>     self._load_state_dict_in_model(state_dict)
>   File "/home/dzge/.conda/envs/workspace/lib/python3.8/site-packages/transformers/trainer.py", line 1412, in _load_state_dict_in_model
>     if set(load_result.missing_keys) == set(self.model._keys_to_ignore_on_save):
>   File "/home/dzge/.conda/envs/workspace/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'CondenserForPretraining' object has no attribute '_keys_to_ignore_on_save'

I cannot continue training with either bert-base-uncased or Luyu/condenser model. I already downloaded it and put in a local folder. 

Thank you.

**Comment by luyug** [comment]
More recent versions of `transformers` have this new check with `_keys_to_ignore_on_save`.

You will see this error if you initialize with a local set of incomplete weights. 
Only when starting with a standard LM like BERT/RoBERTa should you have an incomplete set of weights. These model should come directly from the hub. 

I think this behavior should probably be kept but it should fail more gracefully. I will look into that.

**Comment by CuongNN218** [comment]
@luyug hi everything looks good now. How can I use condenser to encode?

**Comment by luyug** [comment]
@CuongNN218 Can you elaborate on what you are seeking for?

**Comment by CuongNN218** [comment]
I want to encode 2 sentences and find the similarity between them.

**Comment by luyug** [comment]
@CuongNN218 Pre-trained Condenser models can be into with Huggingface AutoModel classes . You can then use the Huggingface APIs to do fine-tuning and inference. For more specific questions, please feel free to open a new issue to provide more details.
