### ISSUE TITLE
Whole word masking for RoBERTa

### ISSUE THREAD

**Issue by eugene-yang** [luyug/Condenser#8]
Can you elaborate on why the first token is appended as an integer instead of `[i]` in line 65? 
If the first word is being separated by BPE, this seems to be resulting in an uncaught exception for the following token. 

https://github.com/luyug/Condenser/blob/de9c2577a16f16504a661039e1124c27002f81a8/data.py#L61

**Comment by luyug** [comment]
What exception are you seeing?

**Comment by eugene-yang** [comment]
It is complaining about an integer doesn't have method `.append`.

**Comment by luyug** [comment]
Right, that probably needs to be fixed.

**Comment by luyug** [comment]
Fixed at TOT.
